### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by vofen430** [AsHfIEXE/Spotify-Music-Downloader#5]
Hi AsHfIEXE,

I hope you're doing well. I recently encountered an issue with the Spotify Web Downloader after reinstalling my operating system. The tool was working fine until a few days ago, but now I’m getting the following traceback error:
```
Traceback (most recent call last):
  File "D:\Python\Python312\Lib\site-packages\spotify_web_downloader\cli.py", line 490, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\spotify_web_downloader\downloader_song.py", line 71, in get_decryption_key
    license = self.downloader.spotify_api.get_widevine_license_music(challenge)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python312\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 112, in get_widevine_license_music
    check_response(response)
  File "D:\Python\Python312\Lib\site-packages\spotify_web_downloader\utils.py", line 10, in check_response
    _raise_response_exception(response)
  File "D:\Python\Python312\Lib\site-packages\spotify_web_downloader\utils.py", line 14, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 403:
[INFO     01:51:54] Done (1 error(s))
```
This error started occurring only after I reinstalled my system. The downloader worked perfectly two days ago, before the reinstallation. I have confirmed that cookie.txt was correctly obtained and placed in the ./ directory as per the usual process. Could this be related to missing dependencies, or possibly a change in API authentication that I might need to update? Do you have any suggestions on how I could resolve this issue?

Thank you for your help!

**Comment by AsHfIEXE** [comment]
It seems  the hard coded WVD got blocked by Spotify. I'll fix this in next update. Many users are facing this issue. Please be patient  and stay tuned for next update.

**Comment by AsHfIEXE** [comment]
Fixed issue. Just update the script
