### ISSUE TITLE
Widevine issue since update?

### ISSUE THREAD

**Issue by ClosetGeek-Git** [AsHfIEXE/Spotify-Music-Downloader#7]
403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

```
[ERROR    14:11:47] (URL 1/2) Failed to check "true"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 392, in main
    url_info = downloader.get_url_info(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader.py", line 95, in get_url_info
    raise Exception("Invalid URL")
Exception: Invalid URL
[INFO     14:11:47] (Track 1/1 from URL 2/2) Downloading "Rise Up"
[ERROR    14:11:48] (Track 1/1 from URL 2/2) Failed to download "Rise Up"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 72, in _check_response
    response.raise_for_status()
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 468, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader_song.py", line 69, in get_decryption_key
    license = self.downloader.spotify_api.get_widevine_license_music(challenge)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 101, in get_widevine_license_music
    self._check_response(response)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 74, in _check_response
    raise Exception(
Exception: Request failed with status code 403:
[INFO     14:11:48] Done (2 error(s))
```

**Comment by ClosetGeek-Git** [comment]
When I go to 'https://gue1-spclient.spotify.com/widevine-license/v1/audio/license' within the browser it responds 'no token provided'

**Comment by ClosetGeek-Git** [comment]
Also, it is saying I'm using a free account when I'm premium. I logged out of my Spotify within chrome, logged back in, copied new cookie to cookies.txt in root of where I'm downloading but still thinks I'm on a free account
```
[WARNING  14:20:43] Free account detected, lyrics will not be downloaded
[ERROR    14:20:43] (URL 1/2) Failed to check "true"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 392, in main
    url_info = downloader.get_url_info(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader.py", line 95, in get_url_info
    raise Exception("Invalid URL")
Exception: Invalid URL
[INFO     14:20:44] (Track 1/1 from URL 2/2) Downloading "Rise Up"
[ERROR    14:20:44] (Track 1/1 from URL 2/2) Failed to download "Rise Up"
Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 72, in _check_response
    response.raise_for_status()
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://gue1-spclient.spotify.com/widevine-license/v1/audio/license

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 468, in main
    decryption_key = downloader_song.get_decryption_key(pssh)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\downloader_song.py", line 69, in get_decryption_key
    license = self.downloader.spotify_api.get_widevine_license_music(challenge)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 101, in get_widevine_license_music
    self._check_response(response)
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 74, in _check_response
    raise Exception(
Exception: Request failed with status code 403:
[INFO     14:20:44] Done (2 error(s))
```

**Comment by ClosetGeek-Git** [comment]
A new error:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Scripts\spotify-web-downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\cli.py", line 317, in main
    spotify_api = SpotifyApi(cookies_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 39, in __init__
    self._setup_session()
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python311\Lib\site-packages\spotify_web_downloader\spotify_api.py", line 61, in _setup_session
    token = re.search(r'accessToken":"(.*?)"', home_page).group(1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by AsHfIEXE** [comment]
Yes. Many users are facing this issue. Just be patient. I'm working on it

**Comment by AsHfIEXE** [comment]
Use this command` pip install spotify-web-downloader -U `

**Comment by ClosetGeek-Git** [comment]
I don't have the .wvd file, and from what I'm seeing you need to put 'Rooted Android Device' at the very top of your list of prerequisites.

**Comment by AsHfIEXE** [comment]
> I don't have the .wvd file, and from what I'm seeing you need to put 'Rooted Android Device' at the very top of your list of prerequisites.

After Update 1.8 prerequisites and installing is little bit different from earlier version

**Comment by AsHfIEXE** [comment]
Rinstall the tool by following the instructions
